# Generated by Django 3.0.3 on 2020-03-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20200321_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='privacy',
            field=models.CharField(choices=[('Private', 'Private'), ('Public', 'Public')], default='Public', max_length=100),
        ),
    ]
