# Generated by Django 3.0.3 on 2020-03-21 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_privacy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='privacy',
        ),
    ]
